### ISSUE TITLE
QC app: "undo" option possible?

### ISSUE THREAD

**Issue by richardsc** [dankelley/oceglider#90]
I know the instructions say that it is not possible to "undo" mouse brushing, but is there a way to include this in the app? Seems like if a record is kept of the brushed points, that they could be undone somehow.

(writing this because while playing around, I forgot that the mouse applies the flag and tried to use it to "zoom in" to a region ... :P )

**Comment by dankelley** [comment]
This comment is coming up to its 5 year anniversary, so I'm going to go ahead and close it.  It's just not at a great place in the 'required' versus 'easy' space.
